name: Bug Report
description: Create bug report for DVModAPI
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        This form is for reporting bugs only.
  - type: input
    id: osVer
    attributes:
      label: OS version/build
      description: What is your OS version
      placeholder: ex. Windows 10 1709 (16299.248)
    validations:
      required: true
  - type: input
    id: DVModAPIver
    attributes:
      label: DVModAPI version
      description: What is your DVModAPI version
      placeholder: ex. 0.1
    validations:
      required: true
  - type: input
    id: UMMVer
    attributes:
      label: Unity Mod Manager version
      description: What is your UMM version
      placeholder: ex. 0.27.5
    validations:
      required: true     
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Describe bug, what happened and what supposed to happen.
      placeholder: Describe bug here...
    validations:
      required: true      
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: To make your bug report valid please attach "player.log" and "Log.txt" from **Derail Valley\DerailValley_Data\Managed\UnityModManager**. Also you can attach screenshots here.
      placeholder: Drag and drop player.log and Log.txt here
    validations:
      required: true          